// This file has been autogenerated from a class added in the UI designer.

using System;
using Assessment.Models;
using Foundation;
using UIKit;
using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;


namespace Assessment.iOS
{
    public partial class CreateReminderListViewController : UIViewController
	{
		public ReminderListsViewModel ViewModel;
        public string SelectedColor;

        public CreateReminderListViewController() { }
        public CreateReminderListViewController (IntPtr handle) : base (handle)
		{
		}
        

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            StyleUI();
            BindUI();

            
        }

        void StyleUI()
        {
            viewColorDisplay.Layer.CornerRadius = 5;
        }

        void BindUI()
        {
            btnSaveUser.TouchUpInside += (sender, e) =>
            {

                var list = new ReminderList
                {
                    Title = txtTitle.Text,
                    Color = SelectedColor,
                    CreatedDate = DateTime.Now
                };
                ViewModel.AddReminderListCommand.Execute(list);
                this.DismissModalViewController(true);
            };

            btnCancel.TouchUpInside += (sender, e) =>
            {
                this.DismissModalViewController(true);
            };

            btnSelectColor.TouchUpInside += (sender, e) =>
            {
                var picker = new UIColorPickerViewController();
                picker.Delegate = new CreateReminderListViewColorPickerDelegate(this);
                PresentModalViewController(picker, true);
            };
        }

        public void SetHexColor(string hexColor)
        {
            SelectedColor = hexColor;
            //lblColorLabel.Text = SelectedColor;
            viewColorDisplay.BackgroundColor = Color.FromHex(SelectedColor).ToUIColor();
        }
    }

    public class CreateReminderListViewColorPickerDelegate : UIColorPickerViewControllerDelegate
    {
        CreateReminderListViewController Parent;
        public CreateReminderListViewColorPickerDelegate(CreateReminderListViewController parent)
        {
            Parent = parent;
        }

        public override void DidSelectColor(UIColorPickerViewController viewController)
        {
            var color = viewController.SelectedColor;
            Parent.SetHexColor(color.ToColor().ToHex());

        }
    }
}
